language: java
before_install: bash libs/install_libs.sh


addons:
  sonarcloud:
    organization: "eskimo-sh-sonarqube-key"
    token:
      secure: "IlEwWo382/auJd4sNnGyy5XBqIcQiR8/qwDSST8wMAD5ohmw9khwbCV1COKFQ29//DCt1gc9hpEkqdaQS2qIh9TV/3jh57LJLio4tGfKqS35938eCoNp9RK5BU9kkkgj657VPiiujy5jGD0/qjnzByoyeinXBKt/HkvXaZ7YmloyxlNOgXY25b1BRpbzL3TmBH0QVMMqD/NIM61Ezf3ewy9gJ1ry8g3tNHxkxyn2Sa7BTLVIog4k41V+F5DYH+ZrJHSd/5V5OuYsqcXZJ61f7VxIeJEu4hM4LuogtanurY/6uRj4eM4VcIiMr/FN09dagGOQ38JLmg9UrOxbit+kjpP0XoNE9ubff1DmHa3VnQEm6VE6OpuaV51VOTHayN5cyH59uzZZSM8I0G6rS4S4oRDxHs9DFwwdw8RiK6i4+ddGehf3SY3dGLr5jt//Mhp/ZaiZhS8uwvFNRvLerKCaPPm9CuZ+Dn4ZI+nwT+T5WpMKWUIaznfHf6fYcCAPNg3hjg9sVGKhuK1t3k0wfPqmywod/CMXYZv6XqFc2Y8O4PYc/EfEvRjBkcFUgXX/1+V+NhFj2BF934nZvm/9wfgiYY733JNZhGAOJZz8vpDo1Q0xvfmR4uwYPc+I61DMSgOLK2/PoUq5AUNwA6/QhLuWroP4joW5J63ov5yVbHItwUA="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=eskimo-sh_eskimo