{
 "title": "Eskimo System Wide Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cluster CPU Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node\"}) by (cpu, instance))",
     "legendFormat": "Physical"
    },
    {
     "expr": "mesos_master_cpus{type=\"total\"}",
     "legendFormat": "Mesos"
    }
   ]
  },
  {
   "title": "Cluster RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node\"})",
     "legendFormat": "Phyical"
    },
    {
     "expr": "mesos_master_mem{type=\"total\"} * 1024 * 1024",
     "legendFormat": "Mesos"
    }
   ]
  },
  {
   "title": "Cluster Disk",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{job=~\"node\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Physical"
    },
    {
     "expr": "mesos_master_disk{type=\"total\"} * 1024 * 1024",
     "legendFormat": "Mesos"
    }
   ]
  },
  {
   "title": "Global Cluster load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_load1{job=\"node\"})"
    }
   ]
  },
  {
   "title": "Overall CPU Consumption",
   "type": "graph",
   "description": "Overall CPU Consumption across whole Eskimo Cluster",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(rate(node_cpu_seconds_total{mode!='idle',job=~\"node\"}[5m])) by (instance)) * 100",
     "legendFormat": "Percentage CPU"
    }
   ]
  },
  {
   "title": "Cluster Wide RAM Monitoring",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node\"})",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node\"}) - sum(node_memory_MemFree_bytes{job=\"node\"}) - (sum(node_memory_Cached_bytes{job=\"node\"}) + sum(node_memory_Buffers_bytes{job=\"node\"}))",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{job=\"node\"}) + sum(node_memory_Buffers_bytes{job=\"node\"})",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{job=\"node\"})",
     "legendFormat": "RAM Free"
    }
   ]
  }
 ]
}