////
This file is part of the eskimo project referenced at www.eskimo.sh. The licensing information below apply just as
well to this individual file than to the Eskimo Project as a whole.

Copyright 2019 www.eskimo.sh - All rights reserved.
Author : http://www.eskimo.sh

Eskimo is available under a dual licensing model : commercial and GNU AGPL.
If you did not acquire a commercial licence for Eskimo, you can still use it and consider it free software under the
terms of the GNU Affero Public License. You can redistribute it and/or modify it under the terms of the GNU Affero
Public License  as published by the Free Software Foundation, either version 3 of the License, or (at your option)
any later version.
Compliance to each and every aspect of the GNU Affero Public License is mandatory for users who did no acquire a
commercial license.

Eskimo is distributed as a free software under GNU AGPL in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Affero Public License for more details.

You should have received a copy of the GNU Affero Public License along with Eskimo. If not,
see <https://www.gnu.org/licenses/> or write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
Boston, MA, 02110-1301 USA.

You can be released from the requirements of the license by purchasing a commercial license. Buying such a
commercial license is mandatory as soon as :
- you develop activities involving Eskimo without disclosing the source code of your own product, software,
  platform, use cases or scripts.
- you deploy eskimo as part of a commercial product, platform or software.
For more information, please contact eskimo.sh at https://www.eskimo.sh

The above copyright notice and this licensing notice shall be included in all copies or substantial portions of the
Software.
////


:sectnums:
:authors: www.eskimo.sh / 2019
:copyright: www.eskimo.sh / 2019

== Eskimo Introduction

Eskimo is a Big Data Management Web Console to _build_, _manage_ and _operate_
*Big Data 2.0* clusters using *Docker* and *Mesos*.

Reach https://www.eskimo.sh for more information on Eskimo or look at the documentation in the folder `doc`.

=== Eskimo Service Development Framework

The *Service Development framework* is actually composed by two distinct parts:

1. The *Docker Images Development Framework* which is used to build the docker images deployed on the eskimo cluster
nodes
2. The *Services Installation Framework* which is used to install these images as services on the eskimo cluster nodes.

This document presents "1. The *Docker Images Development Framework*"




// marker for inclusion : line 60
[[docker_images_development_framework]]

== Docker Images Development Framework

Eskimo manages services (e.g. Flink, Kafka, ElasticSearch, Kibana, etc.) as Docker containers. A docker container is
the individual and single unit representing a service to be managed by Eskimo. +
Docker containers packaging eskimo services should be most of the time downloaded from the Eskimo online package
archive. But an administrator can very well decide to build his own versions of Eskimo Provides service containers or
event develop his own service packages. +
This is described in this section.

The _Docker Images Development Framework_ provides tools and defines standards to build the docker images deployed on the
eskimo cluster nodes.

Eskimo is leveraging on docker to deploy services across the cluster nodes and to ensure independence from host
OSes and specificities as well as proper isolation between services.

Again, Docker images can be downloaded from internet (or the internal corporation network) or build locally on the machine
running eskimo.

=== Requirements

In order for one to be able to either build the eskimo software components packages locally (or have eskimo building
them locally), there are a few requirements:

* Docker must be installed and available on the user local computer or the eskimo host machine in case Eskimo builds
them.
* At least 10Gb of hard drive space on the partition hosting `/tmp` must be available.
* At least 15Gb of hard drive space on the partition histing the eskimo installation folder must be available.

=== Principle

The principle is pretty straightforward

* Every docker image (or package) is built by calling `build.sh` from the corresponding package folder, i.e. a
sub-folder of this very folder `packages_dev`
* That `build.sh` script is free to perform whatever it wants as long as the result is a docker image with the expected
name put in the folder `packages_distrib` in the parent folder and packaging the target software component.

Build files are provided for each and every service pre-packaged within eskimo.

The user is welcome to modify them in order to fine tune everything the way he wants or implement his own packages for
other software components not yet bundled with eskimo. +
Again, the only requirement is that at the end of the build process a corresponding image is put in `packages_distrib`
as well as that some conventions are properly followed as explained below.

Internet is usually required on the eskimo machine to build or re-build the eskimo provided pre-packages images since
the target software component is downloaded from Internet.

=== property 'system.packagesToBuild' in eskimo.properties

Eskimo needs a way during initial setup time to know which packages need to be built or downloaded.

This is indicated by the property `system.packagesToBuild` in the configuration file `eskimo.properties`, such as, for
instance:

.default `system.packagesToBuild` property
----
system.packagesToBuild=base-eskimo,ntp,zookeeper,gluster,elasticsearch,cerebro,kibana,logstash,prometheus,grafana,kafka,kafka-manager,mesos-master,spark,zeppelin
----

Whenever one wants to implement a new package for a new service to be managed by eskimo, one needs to declare this new
package in the given list.

=== Standards and conventions over requirements

There are no requirements when building an eskimo package docker image. The image developer is free to install the
software package within the image the way he wants and no specific requirement is enforced by eskimo.

As long as eventually, _The Service Installation framework_ for the new  software package provides a systemd unit
configuration file enabling the eskimo framework to manipulate the service, a service developer has all the freedom to
design his docker container the way he wants.

However, adhering to some conventions eases a lot the maintenance and evolution of these images. +
These standard conventions are as follows:

* All docker images are based on the `base-eskimo` image which is itself based on a lightweight debian stretch image.
* A software component named _X_ with _version Y_ should be installed in `/usr/local/lib/_x_-_y_` (if and only if it is
not available in apt repositories and installed using standard debian `apt-get install x`).
** In this case, a simlink preventing the further *Services Installation framework* from the need to mess with version
numbers should be created : `/usr/local/lib/x` pointing to `/usr/local/lib/x-version`.
** This simlink is pretty important. In the second stage, when installing services on eskimo cluster nodes, it is
important that setup and installation scripts can be prevented from knowing about the version of the software
component. Hence the important of that simlink.
* The presence of a single `build.sh` script is a requirement. That script is called by eskimo to build the package if
it is not yet available (either built or downloaded)
* A helper script `../common/common.sh` can be linked in the new package build folder using
`ln -s ../common/common.sh common.sh`. This common script provides various helper functions to build the docker
container, save it to the proper location after build, etc.
* The script performing the _in container installation_ of the software component X should be called `installX.sh`.
* Software versions to be downloaded and extracted within docker images are coded _once and for all_ in the file
`../common/common.sh`. This is actually a requirement since most of the time software version for common components such
as ElasticSearch or scala are used in several different packages. Defining version numbers of software components to be
downloaded and installed in a common place helps to enforce consistency.

An eskimo component package developer should look at pre-packaged services to get inspired and find out how eskimo
packaged services are usually implemented.

=== Typical build.sh process

==== Operations performed

The build process implemented as a standard in the `build.sh` script has two different stages:

. The container preparation and all the container setup operated from outside the container
. The software installation done from inside the container

As a convention, all dependencies installation is performed from outside the container but then the installation of the
software packaged in the container is performed from a script called within the container (script `installX.sh` for
package X).

The build process thus typically looks this way:

1. From outside the container:
* Creation of the container from the base eskimo image (debian based)
* Installation of the prerequisites (Java JDK, Scala, python, etc.) using `docker exec ...`
* Calling of the software installation script : `docker exec -it ... installX.sh`

2. From inside the container:
* Downloading of the software from internet
* Installation in a temporary folder
* Moving of the installation software to `/usr/local/lib/X-Version` or else
* symlinking the software from `/usr/local/lib/X` (without version number)

And that's it.

The package installation is limited to this, all the customizations is done at a later stage, during the *Service
Installation* on eskimo cluster noes.

=== Look for examples and get inspired

Look at the eskimo pre-packaged component packages development scripts for examples and the way they are built to get
inspired for developing your own packages.


=== Apache Mesos Building

Bulding Apache Mesos is a different story. There are two different components:

* The *Mesos Master* which runs in a docker container just as every other service within Eskimo. The Mesos Master is
responsible for orchestrating the resources requests and manages offering.
* The *Mesos Agent* which runs natively on the Host OS.  The Mesos Agent is responsible for understanding the available
resources on every node of the Eskimo cluster and answers offers.

The reason why the Mesos Agent runs natively is that it needs to have low level access to the machine to understand its
topology and the available resources. To be transparent, it could run as a docker container as well but that comes with
some limitations that are not acceptable for a production cluster.

*The Mesos Agent is the single and only component running natively within Eskimo* (understand, not in a docker
container).

As such, Mesos is build natively and mesos packages are tarballs (`tar.gz`) to be extracted on the Host OS on every
node.

In this very folder (`packages_dev`) eskimo provides a build framework for Mesos. +
Currently Mesos is built for three targets : RHEL based (RHEL, CentOS, Fedora, etc.) and Debian based (Debian, Ubuntu,
etc.) and SUSE.


==== Building Mesos

The Eskimo build system for Mesos is based on Vagrant and either VirtualBox or libvirt + QEMU/kvm. Vagrant takes care
of building VMs using either VirtualBox or LibVirt, installs all the required packages for building mesos, builds mesos
and creates installable packages.

.For instance, toBuild Mesos package for Debian
----
..../packages_dev$ ./build.sh mesos-deb # for building mesos debian distrib with libvirt
..../packages_dev$ ./build.sh -b mesos-deb # for building mesos debian distrib with VirtualBox
----

These both commands require vagrant and VirtualBox, respectively libvirt, kvm and the libvirt vagrant provider properly
installed.


=== Specific and various notes related to individual components shipped with Eskimo

This section presents different important notes related to some specific services shipped with Eskimo building aspects.

==== Zeppelin building

Zeppelin can be built from a checkout of the latest git repository master or from an official release.

The file `common/common.sh` defines a variable `ZEPPELIN_IS_SNAPSHOT` which, when defined to true, causes the build
system to work from git and rebuilt zeppelin from the sources instead of downloading a released package.

----
export ZEPPELIN_IS_SNAPSHOT="false" # set to "true" to build zeppelin from zeppelin git master
----

Importantly, zeppelin will be build in the folder `/tmp/` of the host machine running eskimo (using a docker container
though) which maps `/tmp` to its own `/tmp`). +
*At least 20 GB of storage space needs to be available in `/tmp` of the machine running eskimo for the build to
succeed.*


=== Setting up a remote packages repository

When running eskimo, software packages - either service docker images or mesos binary packages - can be either built
or downloaded from a *remote packages repository*.

Setting up a remote packages repository is extremely simple:

* The software packages need to be downloadable from internet at a specific URL using either HTTP or HTTPS.
* at the same location where packages are downloaded, a meta-data file should be downloadable and present the various
available packages.

For instance the following layout should be available from internet or the local network:

* *https://www.niceideas.ch/eskimo/eskimo_packages_versions.json*
* https://www.niceideas.ch/eskimo/docker_template_base-eskimo_0.2_1.tar.gz
* https://www.niceideas.ch/eskimo/docker_template_cerebro_0.8.4_1.tar.gz
* https://www.niceideas.ch/eskimo/docker_template_elasticsearch_6.8.3_1.tar.gz
* https://www.niceideas.ch/eskimo/docker_template_flink_1.9.1_2.tar.gz
* https://www.niceideas.ch/eskimo/docker_template_gluster_debian_09_stretch_1.tar.gz
* etc.
* https://www.niceideas.ch/eskimo/eskimo_mesos-debian_1.8.1_1.tar.gz
* https://www.niceideas.ch/eskimo/eskimo_mesos-redhat_1.8.1_1.tar.gz
* etc.

A software package should be named as follows:

* `docker_template_[software]\_[software_version]_[eskimo_version].tar.gz` for service docker images
* `eskimo_mesos-[platform]\_[software_version]_[eskimo_version].tar.gz` for service mesos packages

The file `eskimo_packages_versions.json` describes the repository of packages and the available packages.

.Example eskimo_packages_versions.json
----
{
  "base-eskimo" : {
    "software" : "0.2",
    "distribution" : "1"
  },
  "cerebro": {
    "software": "0.8.4",
    "distribution": "1"
  },
  "elasticsearch" : {
    "software": "6.8.3",
    "distribution": "1"
  },
  "flink" : {
    "software" : "1.9.1",
    "distribution": "1"
  },
  "gluster": {
    "software" : "debian_09_stretch",
    "distribution": "1"
  },
  ...
  "mesos-redhat": {
    "software": "1.8.1",
    "distribution": "1"
  },
  "mesos-debian": {
    "software": "1.8.1",
    "distribution": "1"
  },
  ...
}
----

It's content should be aligned with the following properties from the configuration file `eskimo.properties`:

* `system.packagesToBuild` giving the set of docker images for packages to be or downloaded
* `system.mesosPackages` giving the name of the mesos packages to built or downloaded













// marker for exclusion : line 340

[appendix]
== Copyright and License


Eskimo is Copyright 2019 - 2022 eskimo.sh - All rights reserved. +
Author : https://www.eskimo.sh

Eskimo is available under a dual licensing model : commercial and GNU AGPL. +
If you did not acquire a commercial licence for Eskimo, you can still use it and consider it free software under the
terms of the GNU Affero Public License. You can redistribute it and/or modify it under the terms of the GNU Affero
Public License  as published by the Free Software Foundation, either version 3 of the License, or (at your option)
any later version. +
Compliance to each and every aspect of the GNU Affero Public License is mandatory for users who did no acquire a
commercial license.

Eskimo is distributed as a free software under GNU AGPL in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Affero Public License for more details.

You should have received a copy of the GNU Affero Public License along with Eskimo. If not,
see <https://www.gnu.org/licenses/> or write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
Boston, MA, 02110-1301 USA.

You can be released from the requirements of the license by purchasing a commercial license. Buying such a
commercial license is mandatory as soon as :

* you develop activities involving Eskimo without disclosing the source code of your own product, software,  platform,
  use cases or scripts.
* you deploy eskimo as part of a commercial product, platform or software.

For more information, please contact eskimo.sh at https://www.eskimo.sh

The above copyright notice and this licensing notice shall be included in all copies or substantial portions of the
Software.