#!/bin/bash

#
# This file is part of the eskimo project referenced at www.eskimo.sh. The licensing information below apply just as
# well to this individual file than to the Eskimo Project as a whole.
#
# Copyright 2019 - 2023 eskimo.sh / https://www.eskimo.sh - All rights reserved.
# Author : eskimo.sh / https://www.eskimo.sh
#
# Eskimo is available under a dual licensing model : commercial and GNU AGPL.
# If you did not acquire a commercial licence for Eskimo, you can still use it and consider it free software under the
# terms of the GNU Affero Public License. You can redistribute it and/or modify it under the terms of the GNU Affero
# Public License  as published by the Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
# Compliance to each and every aspect of the GNU Affero Public License is mandatory for users who did no acquire a
# commercial license.
#
# Eskimo is distributed as a free software under GNU AGPL in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero Public License for more details.
#
# You should have received a copy of the GNU Affero Public License along with Eskimo. If not,
# see <https://www.gnu.org/licenses/> or write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA, 02110-1301 USA.
#
# You can be released from the requirements of the license by purchasing a commercial license. Buying such a
# commercial license is mandatory as soon as :
# - you develop activities involving Eskimo without disclosing the source code of your own product, software,
#   platform, use cases or scripts.
# - you deploy eskimo as part of a commercial product, platform or software.
# For more information, please contact eskimo.sh at https://www.eskimo.sh
#
# The above copyright notice and this licensing notice shall be included in all copies or substantial portions of the
# Software.
#

# Mock implementation of kubectl for unit testing

if [[ "$*" == "get pod --all-namespaces -o custom-columns=NAME:metadata.name" ]]; then

    echo "NAME
cerebro-5bc7f5874b-w9x88
elasticsearch-0
elasticsearch-1
elasticsearch-2
flink-runtime-7b8cccbb79-4m4gn
grafana-5c4dd9848d-cmbkz
kafka-0
kafka-1
kafka-2
kafka-manager-6b4c89dc9b-dtfpq
kibana-6d7656c9c5-tlmwp
logstash-0
logstash-1
logstash-2
spark-console-69bf57d949-sb2bh
zeppelin-9f6d88d6f-5pwcf
coredns-5d8697db8f-vr459
dashboard-metrics-scraper-78f56fbd8b-78bz2
kubernetes-dashboard-789fd6b89-t9xnb"

    exit

fi


if [[ "$*" == "get pods --all-namespaces -o custom-columns=NAME:metadata.name,NODE:status.hostIP" ]]; then

    echo "NAME                                         NODE
cerebro-5bc7f5874b-w9x88                     192.168.56.31
elasticsearch-0                              192.168.56.31
elasticsearch-1                              192.168.56.32
elasticsearch-2                              192.168.56.33
flink-runtime-7b8cccbb79-4m4gn               192.168.56.31
grafana-5c4dd9848d-cmbkz                     192.168.56.31
kafka-0                                      192.168.56.31
kafka-1                                      192.168.56.32
kafka-2                                      192.168.56.33
kafka-manager-6b4c89dc9b-dtfpq               192.168.56.31
kibana-6d7656c9c5-tlmwp                      192.168.56.31
logstash-0                                   192.168.56.31
logstash-1                                   192.168.56.32
logstash-3                                   192.168.56.33
spark-console-69bf57d949-sb2bh        192.168.56.31
zeppelin-9f6d88d6f-5pwcf                     192.168.56.31
coredns-5d8697db8f-vr459                     192.168.56.31
dashboard-metrics-scraper-78f56fbd8b-78bz2   192.168.56.31
kubernetes-dashboard-789fd6b89-t9xnb         192.168.56.31"

    exit

fi


if [[ "$*" == "get pod --all-namespaces -o custom-columns=NAME:metadata.name,NAMESPACE:metadata.namespace" ]]; then

    echo "NAME                                         NAMESPACE
cerebro-5bc7f5874b-w9x88                      eskimo
elasticsearch-0                               eskimo
elasticsearch-1                               eskimo
elasticsearch-2                               eskimo
flink-runtime-7b8cccbb79-4m4gn                eskimo
grafana-5c4dd9848d-cmbkz                      eskimo
kafka-0                                       eskimo
kafka-1                                       eskimo
kafka-2                                       eskimo
kafka-manager-6b4c89dc9b-dtfpq                eskimo
kibana-6d7656c9c5-tlmwp                       eskimo
logstash-0                                    eskimo
logstash-1                                    eskimo
logstash-2                                    eskimo
spark-console-69bf57d949-sb2bh         eskimo
zeppelin-9f6d88d6f-5pwcf                      eskimo
coredns-5d8697db8f-vr459                     kube-system
dashboard-metrics-scraper-78f56fbd8b-78bz2   kubernetes-dashboard
kubernetes-dashboard-789fd6b89-t9xnb         kubernetes-dashboard
"

    exit

fi



echo "$*"