{
 "title": "Eskimo Mesos Agents Monitoring",
 "description": "Dashboard based on Mesos official collector (https://github.com/mesos/mesos_exporter)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(mesos_slave_task_labels,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Mesos Slave Allocated Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mesos_slave_mem{type=\"percent\",instance='$node'} * 100.0"
    }
   ]
  },
  {
   "title": "Mesos Allocated CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": " mesos_slave_cpus{type=\"percent\",instance='$node'} * 100"
    }
   ]
  },
  {
   "title": "Mesos Slave Memory Revocable",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mesos_slave_mem_revocable{type=\"percent\",instance='$node'}"
    }
   ]
  },
  {
   "title": "Mesos Revocable CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "mesos_slave_cpus_revocable{type=\"percent\",instance='$node'}"
    }
   ]
  },
  {
   "title": "Terminated Executors Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mesos_slave_executors_terminated{instance='$node'}"
    }
   ]
  },
  {
   "title": "Number of Mesos Agents",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mesos_slave_registered{instance='$node'}"
    }
   ]
  },
  {
   "title": "Max Executor age",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mesos_slave_executor_directory_max_allowed_age_secs{instance='$node'}"
    }
   ]
  },
  {
   "title": "Mesos running executors statustics",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_slave_executor_state{instance='$node',state='registering'}",
     "legendFormat": "registering"
    },
    {
     "expr": "mesos_slave_executor_state{instance='$node',state='running'}",
     "legendFormat": "running"
    },
    {
     "expr": "mesos_slave_executor_state{instance='$node',state='terminating'}",
     "legendFormat": "terminating"
    }
   ]
  },
  {
   "title": "Mesos Slave Executors Preempted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_slave_executors_preempted{instance='$node'}"
    }
   ]
  },
  {
   "title": "Mesos Framework statistics logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "mesos_slave_messages_outcomes_total{instance='$node',type='framework',outcome='invalid'}",
     "legendFormat": "framework_invalid"
    },
    {
     "expr": "mesos_slave_messages_outcomes_total{instance='$node',type='framework',outcome='valid'}",
     "legendFormat": "framework_valid"
    },
    {
     "expr": "mesos_slave_messages_outcomes_total{instance='$node',type='status',outcome='invalid'}",
     "legendFormat": "status_invalid"
    },
    {
     "expr": "mesos_slave_messages_outcomes_total{instance='$node',type='status',outcome='valid'}",
     "legendFormat": "status_valid"
    }
   ]
  },
  {
   "title": "Mesos task statistics logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "mesos_slave_task_states_exit_total{instance='$node',state='errored'}",
     "legendFormat": "errored"
    },
    {
     "expr": "mesos_slave_task_states_exit_total{instance='$node',state='failed'}",
     "legendFormat": "failed"
    },
    {
     "expr": "mesos_slave_task_states_exit_total{instance='$node',state='finished'}",
     "legendFormat": "finished"
    },
    {
     "expr": "mesos_slave_task_states_exit_total{instance='$node',state='gone'}",
     "legendFormat": "gone"
    },
    {
     "expr": "mesos_slave_task_states_exit_total{instance='$node',state='killed'}",
     "legendFormat": "killed"
    },
    {
     "expr": "mesos_slave_task_states_exit_total{instance='$node',state='lost'}",
     "legendFormat": "lost"
    }
   ]
  }
 ]
}