{
 "title": "Eskimo System Wide Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total CPU Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node\"}) by (cpu, instance))"
    }
   ]
  },
  {
   "title": "Total available RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node\"})"
    }
   ]
  },
  {
   "title": "Total available SWAP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes{job=\"node\"})"
    }
   ]
  },
  {
   "title": "Total Available disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{job=~\"node\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Global Cluster load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_load1{job=\"node\"})"
    }
   ]
  },
  {
   "title": "Overall CPU Consumption",
   "type": "graph",
   "description": "Overall CPU Consumption across whole Eskimo Cluster",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(rate(node_cpu_seconds_total{mode!='idle',job=~\"node\"}[5m])) by (instance)) * 100",
     "legendFormat": "Percentage CPU"
    }
   ]
  },
  {
   "title": "Individual Nodes CPU Consumption",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!='idle',job=~\"node\"}[5m])) by (instance) * 100"
    }
   ]
  },
  {
   "title": "Cluster Wide RAM Monitoring",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node\"})",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node\"}) - sum(node_memory_MemFree_bytes{job=\"node\"}) - (sum(node_memory_Cached_bytes{job=\"node\"}) + sum(node_memory_Buffers_bytes{job=\"node\"}))",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{job=\"node\"}) + sum(node_memory_Buffers_bytes{job=\"node\"})",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{job=\"node\"})",
     "legendFormat": "RAM Free"
    }
   ]
  }
 ]
}