FROM eskimo/spark:$COMMON_CONTAINER_TAG

MAINTAINER eskimo <eskimoapp@gmail.com>

ENTRYPOINT [ "/usr/local/sbin/eskimo-spark-entrypoint.sh" ]

EXPOSE 7077/tcp
EXPOSE 8580/tcp
EXPOSE 8980/tcp
EXPOSE 8581/tcp
EXPOSE 8981/tcp
EXPOSE 2304/tcp
EXPOSE 18480/tcp
EXPOSE 7337/tcp
EXPOSE 7222/tcp
EXPOSE 8032/tcp
EXPOSE 7222/tcp
