FROM eskimo/prometheus_template:latest

MAINTAINER eskimo <eskimoapp@gmail.com>

EXPOSE 9090/tcp
EXPOSE 9091/tcp
EXPOSE 9093/tcp
EXPOSE 9094/tcp

# Node exporter
EXPOSE 9100/tcp

# Other exporters
#EXPOSE 9100/tcp
#EXPOSE 9105/tcp
#EXPOSE 9114/tcp
#EXPOSE 9125/tcp
#EXPOSE 9141/tcp
#EXPOSE 9159/tcp
#EXPOSE 9160/tcp
#EXPOSE 9185/tcp
#EXPOSE 9189/tcp
#EXPOSE 9198/tcp
#EXPOSE 9206/tcp
#EXPOSE 9208/tcp
#EXPOSE 9261/tcp
#EXPOSE 9304/tcp
#EXPOSE 9323/tcp
#EXPOSE 9346/tcp
#EXPOSE 9381/tcp
#EXPOSE 9428/tcp
#EXPOSE 9428/tcp

