FROM eskimo/gluster_template:latest

MAINTAINER eskimo <eskimoapp@gmail.com>

EXPOSE 24007/tcp
EXPOSE 24008/tcp
EXPOSE 24009/tcp
EXPOSE 24010/tcp
EXPOSE 49152/tcp
EXPOSE 38465/tcp
EXPOSE 38466/tcp
EXPOSE 38467/tcp
