# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Install dependencies
      run: ./libs/install_libs.sh
    - name: Build with Maven
      run: mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=eskimo-sh_eskimo -Dsonar.organization=eskimo-sh-sonarqube-key -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=$SONAR_TOKEN --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
